CREATE USER IF NOT EXISTS swift IDENTIFIED BY 'base2';

CREATE DATABASE IF NOT EXISTS world;
CREATE DATABASE IF NOT EXISTS aviaco;

GRANT ALL PRIVILEGES ON aviaco.* TO swift IDENTIFIED BY 'base2';
GRANT SELECT ON world.* TO swift IDENTIFIED BY 'base2';
